#! /bin/bash
#
###
# Usage: pwlconfig [project_name] [Options]
#
#    Configure and maintain Pee Wee Linux Projects for
#    embedded targets. Use from command line or interactively.
#
# Options:
#      -b, --experimental   turn on experimental features
#      -h, --help           dislay this help and exit
#      -v, --version        output version information and exit
#
# Where:
#    project_name     defaults to last project used
#    new_project_name a new name for a project
#    source_dir...    all other parameters default to project defaults
#
#  All other sub-menu operations are available from command line using
#  other PWL scripts. Use --help for each tool in the scripts directory.
###
#
# pwlconfig
#
#    Many (ok, very many) Features copied from Menuconfig script
#    Requires lxdialog from /usr/src/linux/scripts/lxdialog
#
#    Created by Ralph Stickley rstickley@datalux.com
#
#    Built for Pee Wee Linux created by Adi Linden adi@adis.on.ca
#
# Notes:
#
#   pwlconfig is designed entirely around the lxdialog utility as found in 
#   /usr/src/linux/scripts/lxdialog.  All user interface dialogs are displayed
#   and all user keystrokes are handled by lxdialog. 
#
#   The major function groups in this program are:
#      show_xxxx   - wrapper functions that call lxdialog
#      build_xxxx  - functions that create lists for the dialog box
#      extract_xxx - functions that extract files from project list files
#      device_xxx  - functions which deal with the disk on chip device
#      menu_xxx    - handle menu input to execute commands
#
#   Directory Structure used:
#      Package  - location of 'tarballs' optimized for embedded systems
#      scripts  - utility functions
#      projects - location of user configurations and filesystems
#      mnt      - normally where target device is mounted
#
#   Project Files:
#      project.conf - Main configuration file - any tarball listed here
#                     will be extracted into the users filesystem
#      xxx.list     - lists the files to be extracted from each tarball
#      .xxx.list    - configuration in progress file
#
# History
# =======
#
# see scripts/CHANGES.pwlconfig
#
#=============================================================================
#
# Make sure we're really running bash.
#
[ -z "$BASH" ] && { echo "`basename $0` requires bash" 1>&2; exit 1; }
#
#  constants for this shell script
#
#
export usrMode="I"
#
# make sure we're executed from Embedded_Build
#
if [ `basename $PWD` != "Embedded_Build" ] ; then
    echo "+-----+-----+-----+-----+-----+-----+-----+-----+" >&2
    echo " The pwlconfig scripts must be executed from the " >&2
    echo " Embedded_Build directory....                    " >&2
    echo "+-----+-----+-----+-----+-----+-----+-----+-----+" >&2
    # end this right now!
    exit 1
fi
#
# include utility functions
#
. ./scripts/pwl_functions
#
#=============================================================================
#=============================================================================
#
#  show_xxx  - uses lxdialog to show menu items
#              returns the 'tag' the selected item on error stream
#              returns the keyId of the key pressed as function status
#              keyIds are:
#                  0 - user pressed ENTER key with "select" highlighted
#                  1 - user pressed ENTER key with "Exit" highlighted
#                  2 - user pressed '?' or ENTER key with "Help" highlighted
#                       (also returns text of selected item on error stream)
#                  3 - user pressed 'Y' or 'y'
#                  4 - user pressed 'N' or 'n'
#                  5 - user pressed 'M' or 'm'
#                  6 - user pressed ' ' (ignores which button is highlighted)
#                255 - user pressed 'Esc'
#
#  show_main ( main_menu_list )
#
function show_main()
{
   if [ -z "$mainDefault" ] ; then
      mainDefault=config
   fi
   echo -n $DIALOG --title "'Main Menu'"       \
                   --backtitle "'$backtitle'"  \
                   --menu                      \
"'Pee Wee Linux System Menu                   Project: $CFG_BASE'" \
         $ROWS $COLS $((ROWS-8))                                   \
         "'$mainDefault' " > .dialog

   cat $1 >> .dialog
   #
   # execute and return results
   #
   . ./.dialog
}

#=============================================================================
#
# build_main( main_menu_list )
#     creates given file with contents of main menu options
#
function build_main()
{
   $decho "start build_main"
   if [ "$deviceName" = "" ] ; then
       #
       # defective configuration prompt to fix
       #
       show_confirm "Internal error - set device" \
           "No device has been set for this project. Probably because of a corrupted or non existant configuration file. Reset the configuration for $CFG_BASE?" "9"
       if [ $? = "1" ] || [ $? = "255" ]; then
           $decho "Nothing was done. User cancelled..."
           exit 0
       fi
       $PRJ_DEFAULTS --reset FLASH
       if [ "$?" = "1" ] ; then
           cleanup 1
       fi
       default_define   # now load default variables
       $decho "Reset configuration..."
   fi

   echo -n "" >$1

   echo -n " 'PkgConfig' 'Configure Project File System -->' "         >>$1 
   if [ "$pwlExp" = "true" ]; then
       echo -n " 'Update'    'Create or Update \"$CFG_BASE\" from File System (experimental) --> ' " >>$1
   fi
   echo -n " 'Extract'   'Extract File System for Project' "           >>$1
   echo -n " 'skip'      '----' " >>$1
   echo -n " 'Target'    'Configure Target Hardware -->'  "            >>$1
   echo -n " 'Load'      'Load File System onto Target $deviceName' "  >>$1
   echo -n " 'skip'      '----'   "                                    >>$1
   echo -n " 'PrjManage' 'Manage Projects -->' "                       >>$1
   echo -n " 'PkgManage' 'Manage Package Files -->' "                  >>$1
   echo -n " 'Save'      'Save Project' "                              >>$1
   #
   $decho "end build_main"
}

#=============================================================================
#
# extract_custom( mountPoint ) - copy custom files to mount point
#
function extract_custom ()
{
   $decho "start extract_custom"
   echo ""
   fileCount=0

   if [ -f "$PWL_PRJ"/"$CUSTOM_LST" ] ; then
      #
      echo "Copying Custom files as specified in $PWL_PRJ/$CUSTOM_LST "
      echo ""
      #
      $PWL_CUSTOM --extract $1 2> .return
      read fileCount < .return
      $RM -rf .return

   fi
   if [ "$fileCount" = "0" ] ; then
      echo "No Custom Files Copied"

   else
      echo ""
      echo "Custom File Copy done - $fileCount files copied"
      echo ""
   fi
   echo ""
   $decho "end extract-custom"
   $RM .return
}

#
# extract_packages ( mountPoint )
#    Extracts all files specified in a project configuration
#    Every package file listed in CFG_FILE is extracted based on the
#    files listed in that package's <pkg_fn>.list included in the project
#
function extract_packages()
{
   $decho "start extract_packages"
   echo -n Extracting files from:
   $MOVE_TO_COL
   echo as specified in:
   echo ""
   #
   loc=$PWD
   ln=1
   #
   if [ ! -f $CFG_FILE ] ; then
      return
   fi
   for nfile_lst in `cat $CFG_FILE`; do
       #
       # each list file needs it's tar ball untarred at mount point
       #
       pkgDir=`dirname $nfile_lst`
       lst_file=`basename "$nfile_lst"`
       tar_file=`basename $nfile_lst .list`".tar"
       #
       if [ ! -f "$pkgDir"/"$tar_file" ] ; then
          echo "$CFG_FILE Error: $pkgDir/$tar_file not found (line $ln)"

       elif [ ! -f "$PWL_PRJ"/"$lst_file" ] ; then  # internal error ??
             echo Configuration list file $PWL_PRJ/$lst_file not found

       else
          #
          #  nice printout of whats happening
          cd $1
          echo -n $tar_file
          $MOVE_TO_COL
          echo "$CFG_BASE"/"$lst_file"
          #
          # seperate directories and file  (dirs are names that end in '/')
          #  'cause extracting a directory extracts all files found in that directory
          #   *but* not extracting an empty directory doesn't create that directory
          #
          grep -v "\/$" "$loc"/"$PWL_PRJ"/"$lst_file"  > "$loc"/.cfg_files
          grep    "\/$" "$loc"/"$PWL_PRJ"/"$lst_file" | sort -r > "$loc"/.cfg_dirs
          #
          # add back only directories specified that are empty
          #
          for includeDir in `cat $loc/.cfg_dirs` ;
          do
              # if a required directory is not already in the list of
              #  files to extract, add it to the list of files to extract
              #  to allow tar to create an empty directory
              #
              if ! grep -q $includeDir $loc/.cfg_files ; then
                 echo $includeDir >> $loc/.cfg_files
              fi
          done
          #
          # do the actual extraction (-p keeps permmissions)
          # -k does not write over existing files
          # ( Note: tar still gives errors on empty directories that
          #         contain empty directories..you just can't win :()
          #
          $TAR -xpkf "$loc"/"$pkgDir"/"$tar_file" -T "$loc"/.cfg_files 2>&1

          cd $loc
       fi
       #
       ln=`expr $ln + 1`    # increment line counter for debugging
   done
   cd $loc
   #
   echo ""
   echo " Total Size of Package Files extracted: `du $1 -bsh` "
   echo ""
   #
   $RM .tmp .cfg_files .cfg_dirs
   $decho "end extract_packages"
}

#
# extract_project( [mntPt ] )
#     Prompts for the extraction point and extracts files as defined by
#     the project configuration - packages and custom files.
#
function extract_project()
{
   $decho "start extract_project"
   #
   # save changes if any
   #
   confirm_save
   #
   if [ "$1" != "" ] ; then
      mntName="$1"

   else
      get_string "Extract File System for project: $CFG_BASE" \
                 "Enter path and name of mount point:" \
                 "mntName" "$PWL_PRJ"/"$prjMnt"
      if [ $? != "0" -o "$mntName" = "" ] ; then
         return
      fi
   fi
   #
   # extract packages and custom files
   #
   rm -rf $mntName
   mkdir "$mntName"                                   > .extract.log
   #
   if [ ! "$?" = "0" ] ; then
      show_message "Mount Point Not Created" "Error Creating Directory"
      return 0
   fi
   #
   extract_packages "$mntName"                        >> .extract.log 2>&1
   extract_custom   "$mntName"                        >> .extract.log 2>&1
   #
   echo ""                                            >> .extract.log
   echo "Total System File Size: `du $mntName -bsh` " >> .extract.log
   echo ""                                            >> .extract.log
   #
   show_results .extract.log "Extracted File System"
   #
   $RM .extract.log
   $decho "end extract_project"
}

#
# device_load_fs( [ sourceMnt, deviceMntName ])
#    Load file system created for this project onto the current device
#    prompts for source and destination then show results
#
function device_load_fs ()
{
   $decho "start device_load_fs"
   #
   # make sure we have a current default parameters
   # abort if version mismatch or suspected corruption
   #
   $decho "compare versions current $PWL_VER, config $pwl_version"
   if [ -z "$pwl_version" ] ; then
       $decho "bad defaults file..."
       # show message
       show_message "Configuration File Error" \
           'The configuration file is either pre 0.53 or corrupted. Select "Configure Target Hardware" before attempting to load system.'
       $decho "refuse to load target..."
       return 1
   elif [ "$pwl_version" != "$PWL_VER" ]; then    
       $decho "version mismatch..."
       show_message "Configuration Version Mismatch" \
           'The configuration file version does not match the current PeeWeeLinux version. Select "Configure Target Hardware" and upgrade configuration before attempting to load system.' "8"
       $decho "refuse to load target..."
       return 1
   fi
   #
   # ask for confirmation before building system
   #
   show_confirm "Load File System onto Target $deviceName" \
          "You are about to install the extracted filesystem onto $deviceName. All existing content on $deviceName will be destroyed. Are you sure you wish to proceed?" "9"
   if [ $? = "1" ] || [ $? = "255" ]; then
      $decho "Nothing was done. User cancelled..."
      return
   fi
   #
   # execute commands to load the file system to the device
   #
   . ./$PWL_TARGET # >.load.log 
   #
   # show dialog with success or fail
   #
   if [ "$rd_fail" = "fail" ]; then
       #
       # load failed
       #
       show_confirm "Load File System onto Target $deviceName failed" \
           "The target build script failed to load the filesystem onto the configured target. Do you wish to view the results?"
   else
       #
       # load success
       #
       show_confirm "Load File System onto Target $deviceName succeeded" \
           "The target build script succeeded in loading the configured target device. Do you wish to view the results?"
   fi
   #
   # show results if selected
   #
   if [ $? = "1" ] || [ $? = "255" ]; then
       #
       $decho "Skip results..." 
   else
       #
       show_results $rd_log "Load $deviceName Results"
       $decho "Show results..." 
   fi
   #
   $RM  .load.log
   $decho "end device_fs_load"
}

#=============================================================================
#
# menu_main()
#    pwlconfig main menu, interactive operation is here, by golly
#
function menu_main()
{
   $decho "start menu_main"
   #
   mainDone=0
   #
   while [ "$mainDone" = "0" ]; do

      build_main .main.lst                # rebuild everytime - its cheap
      show_main .main.lst 2> .result

      retVal=$?
      read selection <.result
      mainDefault=$selection

      if [ "$retVal" = "1" ]  ; then    # exit -
         mainDone=1                     #     don't 'escape' from main, lets
                                        #     you lay on the esc key and not
                                        #     get kicked out :-)
      elif [ "$retVal" = "2" ] ; then
         show_help menu_main            # help
      else
         case "$selection" in
             "PkgConfig")
                     $PWL_PKGCONF
             ;;
             "Extract")
                     extract_project
             ;;

             "Update")               # compare mounted filesystem with
                                     # files at mount point
                     $PWL_UPDATE
             ;;
             "Target")
                     $PRJ_DEFAULTS
                     default_define
             ;;
             "Load")
                     device_load_fs
             ;;
             "Save")
                     confirm_save
             ;;
             "PkgManage")
                   $PWL_PKGMGR
             ;;
             "PrjManage")
                     confirm_save
                     $PWL_PROJECTS
                     if [ $? = "1" ] ; then # no project selected
                        mainDone=1;
                     else                   # reset defaults
                        pwl_init_project
                        default_define
                     fi
             ;;
        esac
     fi
     #
   done
   # cleanup
   $RM  .select.lst .result .dialog .main.lst
   $decho "end menu_main"
}

#=============================================================================
#
# cleanup
#
function cleanup() 
{
   $decho "start cleanup"
   $RM -f .result .dialog
   $decho "end cleanup"
   if [ "$1" != "" ] ; then  # quit program
      exit $1
   fi
}

#=============================================================================
#
#  main_init() setup project environment - call whenever project changes
#              (multiple calls are ok :-)
#
function main_init()
{
   $decho "start main_init"
   echo -n "."
   #
   export backtitle="Pee Wee Linux System Configuration - Version $PWL_VER"
   progInfo=$backtitle
   #
   # check for initial setup
   #
   pwl_init_project default
   if [ "$?" = "1" ] ; then
      cleanup  #not root user
   fi
   #
   echo -n "."
   export CFG_BASE=none
   $PWL_PROJECTS --init
   status=$?
   if [ "$status" = "1" ] ; then
      # no valid project entered
      cleanup 1
   fi
   #
   # set global project variables
   #
   echo -n "."
   pwl_init_project
   default_define
   if [ "$?" = "1" ] ; then # no default files found, prompt & create
      $PRJ_DEFAULTS --reset FLASH
      if [ "$?" = "1" ] ; then
         cleanup 1
      fi
      default_define   # now load default variables
   fi
   #
   # checking for tar packages
   #
   if [ ! -d $PKG_DIR ]; then
       show_confirm "No packages found" \
           "No tar packages were found. Do you wish to extraxt all binary rpms and create tar packages now (recommended)?"
       #
       # check for user response and take appropriate action
       #
       if [ $? = "1" ] || [ $? = "255" ]; then
           $decho "Nothing was done. User cancelled..."
       else
           $decho "Calling $PWL_PKGMGR to extract rpms..."
	   $PWL_PKGMGR --add-all
	   if [ "$?" = "1" ] ; then
	       $decho "A fatal error occured!"
               cleanup 1
           fi
       fi
   fi		  
   # 
   # verify package files are up to date with source files
   #
   echo -n "."
   $PWL_PKGMGR --update
   #
   # verify custom files are up to date with source files
   #
   echo -n "."
   $PWL_CUSTOM --update
   #
   # create master index of all packages
   #
   echo -n "."
   $PWL_LISTER --index -c $PKG_INDEX
   #
   $decho "end main_init"
}

#
#  cmd_parse_commands - parses command line parameters
#
#      if project name is specified, it must be first parameter
#      on the command line
#
function cmd_parse_commands ()
{
   $decho "start cmd_parse_commands"
   #
   # parse commands
   #
   while [ ! "$1" = "" ] ;
   do
      $decho "Parsing Cmd: $1"
      cmd=$1
      shift
      case "$cmd" in
      "--clean")               # erase all temp package stuff non-menu command
         $PWL_CLEAN
         ;;

      "--clean-factory")
         $PWL_CLEAN --factory
         ;;

      "--debug")                        # undocumented feature!;-)
          if [ $debugMode = "0" ] ; then
             debug_mode  1
          else
             debug_mode 0
          fi
          ;;

      "--help"|"-h")                    # display help
          usage
          exit 0
          ;;

      "--version"|"-v")                 # display version
          echo "`basename $0` (Pee Wee Linux Configuration utility) Version $PWL_VER"
          exit 0
          ;;

      "--experimental"|"-b")            # brave mode, turn on experimental 
          #
          # display disclaimer
          show_message "Experimental Mode: On" \
              "You have choosen to turn on 'experimental' or 'brave' mode. Menu options marked experimental might behaviour different as expected or won't work at all. Use at your own risk!" "9"
          #
          # simply export a variable to show we want it all
          export pwlExp="true"
          ;;
      *)
          usage "$cmd:  not a valid pwlconfig option"
          exit 0
          ;;

      esac
   done
   #
   $decho "end cmd_parse_commands"
}

#=============================================================================
#
# void pwlconfig_main( arg1 arg2 arg3 )
#
#
function pwlconfig_main()
{
   $decho "start pwlconfig_main"
   #
   # error handler
   #
   trap "cleanup ; exit 1" 1 2 15
   #
   #  Handle command line parameters if they exist
   #
   cmd_parse_commands $*
   #
   # select project to start with (last used, first found or create new)
   # - sets all global project variables
   #
   main_init
   #
   # operate the menus
   #
   menu_main
   #
   # Ask to Save configuration
   #
   confirm_save
   #
   cleanup
   $decho "end pwlconfig_main"
}

# start here
   debug_mode 0           # set to 1 to enable debug macros

   $decho "START $0 $*"

   pwlconfig_main $*

   $decho "END $0"

   exit 0
#
# end.
#
